# Generated by Django 5.0.1 on 2024-01-20 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0003_alter_testrealizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestatest',
            name='respuesta_seleccionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examenes.opcionderespuesta'),
        ),
    ]