# Generated by Django 5.0.1 on 2024-01-29 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0005_testrealizado_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia_total', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AsignaturaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.IntegerField(default=0)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenes.asignatura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenes.userprofile')),
            ],
        ),
    ]
