# Generated by Django 5.0.1 on 2024-02-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0007_seccion_subseccion_progresousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
