# Generated by Django 5.0.1 on 2024-02-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0008_pregunta_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='color_fondo',
            field=models.CharField(default='#FFFFFF', help_text='Color de fondo hexadecimal de la sección', max_length=7),
        ),
        migrations.AddField(
            model_name='seccion',
            name='icono_url',
            field=models.ImageField(default='iconos_secciones/default.png', help_text='Icono representativo de la sección', upload_to='iconos_secciones/'),
        ),
    ]
