# Generated by Django 5.0.1 on 2024-02-04 22:14

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0009_seccion_color_fondo_seccion_icono_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='subseccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas', to='examenes.subseccion'),
        ),
        migrations.AddField(
            model_name='subseccion',
            name='contenido_teorico',
            field=markdownx.models.MarkdownxField(default='Texto'),
        ),
    ]
