[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
testpaths = [
    "tests"
]
python_files = [
    "test_*.py",
    "*_test.py"
]
addopts = "-v --tb=short"
filterwarnings = [
    "ignore::pytest.PytestCollectionWarning"
]

[tool.bandit]
exclude_dirs = ["tests"]

[tool.isort]
profile = "black"
line_length = 88

[tool.pylint]
load-plugins = ["pylint_django"]

[tool.pylint.MASTER]
# Pylint configuration
init-hook = "import sys; sys.path.append('/app'); import os; os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')"
ignore = [
    "urls.py",
    "migrations",
    "scripts"
]


[tool.pylint.'FORMAT']
# Configuraciones específicas para el formato del código
max-line-length = 120

[tool.pylint.'MESSAGES CONTROL']
# Desactiva o ajusta las advertencias que puedan entrar en conflicto con Black
disable= [
    "fixme",
    "logging-fstring-interpolation",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
]
